
  

audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  type: transducer
  enc:
      type: lstm
      hidden_size: 320
      output_size: 320
      n_layers: 4
      bidirectional: True
  dec:
      type: lstm
      embedding_size: 512
      hidden_size: 512
      output_size: 320
      n_layers: 2
  joint:
      input_size: 640
      inner_size: 512

  vocab_size: 4866
  feature_dim: 160
  dropout: 0.3
  name : 'rnn-t'
  share_weight: False
  

training:
  epochs: 100
  batch_size: 1
  save_path: "/home/anhkhoa/rnn-t/save_path"
  train_path : "/home/anhkhoa/transformer_transducer_speeQ/data/train_w2i.json"
  dev_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  test_path : "/home/anhkhoa/transformer_transducer_speeQ/data/test_w2i.json"
  vocab_path : "/home/anhkhoa/transformer_transducer_speeQ/data/vocab_w2i.json"
  reload: False
  result: "/home/anhkhoa/rnn-t/inference_results_old.txt"


optim:
  type: sgd
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0
  begin_to_adjust_lr: 60
  nesterov: None
  decay_rate: 0.5


rnnt_loss:
  blank: 4
  reduction: "mean" 